# Generated by Django 4.1.13 on 2024-09-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venture', '0002_venture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('photo', models.URLField(blank=True)),
            ],
        ),
    ]
