# Generated by Django 4.1.13 on 2024-09-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
