# Generated by Django 4.1.13 on 2024-07-05 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=0)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=128)),
                ('restaurant_id', models.CharField(max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('tokenExpirationDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
