# Generated by Django 4.1.13 on 2024-09-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.IntegerField(null=True),
        ),
    ]
