# Generated by Django 4.1.13 on 2024-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_benefit_rename_expired_subscription_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='code_id',
            field=models.IntegerField(null=True),
        ),
    ]
