# Generated by Django 4.1.13 on 2024-09-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_benefit_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='plan_id',
            field=models.IntegerField(null=True),
        ),
    ]
